target ‘RSC’ do
	use_frameworks!

	pod 'Alamofire', '~> 4.0'
	pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
	pod 'IQKeyboardManagerSwift', '4.0.6'
	pod 'Unbox'
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
	pod 'FacebookCore'
    pod 'FacebookLogin'
    
end
